id: Baseline
pretrained: null
seed: 3698
model:
    name: BaselineWithLinear
    args:
        nclasses: 42
        hidden_dim: 512
        extractor_cfg:
            name: ResNetExtractor
            args:
                version: resnet50
optimizer:
    name: Adam
    args:
loss:
    name: CrossEntropyLoss
    args:
metric:
    - name: Accuracy
      args:
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: ShopeeDataset
        args:
            img_dir: data/shopee-product-detection-dataset/train/train
            csv_path: data/list/train_train.csv
            is_train: True
        loader:
            name: DataLoader
            args:
                shuffle: True
                batch_size: 16
    val:
        name: ShopeeDataset
        args:
            img_dir: data/shopee-product-detection-dataset/train/train
            csv_path: data/list/train_val.csv
            is_train: False
        loader:
            name: DataLoader
            args:
                batch_size: 128
trainer:
    nepochs: 200
    val_step: 1
    log_step: 1
    runs: runs
