id: Baseline
pretrained: null
seed: 3698
model:
    name: BaselineClassifier
    args:
        nclasses: 42
        extractor_cfg:
            name: ResNetExtractor
            args:
                version: resnet18
optimizer:
    name: Adam
    args:
loss:
    name: CrossEntropyLoss
    args:
metric:
    - name: Accuracy
      args:
scheduler:
    name: ReduceLROnPlateau
    args:
        patience: 5
        #rate: 0.5
dataset:
    train:
        name: ShopeeDataset
        args:
            img_dir: data/shopee-product-detection-dataset/train/train
            csv_path: data/shopee-product-detection-dataset/train_train.csv
            is_train: True
        loader:
            name: DataLoader
            args:
                shuffle: True
                batch_size: 64
    val:
        name: ShopeeDataset
        args:
            img_dir: data/shopee-product-detection-dataset/train/train
            csv_path: data/shopee-product-detection-dataset/train_val.csv
            is_train: False
        loader:
            name: DataLoader
            args:
                batch_size: 128
trainer:
    nepochs: 200
    val_step: 1
    log_step: 1
